### ISSUE TITLE
Add failed to login message

### ISSUE THREAD

**Issue by nyxcharon** [nyxcharon/vault-ui#1]
Entering the wrong username/password combination doesn't display any errors on the login page

**Comment by kelcecil** [comment]
+1.

**Comment by awestbro** [comment]
+1

**Comment by jdavis92** [comment]
+1

**Comment by alexjpaz** [comment]
![GitHub Logo](http://cultofthepartyparrot.com/parrots/parrot.gif)

**Comment by brendangibat** [comment]
Plus One

**Comment by kelcecil** [comment]
Can the error message contain the parrot? I think we need more parrot.

**Comment by kelcecil** [comment]
What's the status on this? This will solve all of my problems.

**Comment by nyxcharon** [comment]
Implemented, resolving.
