### ISSUE TITLE
Getting started guide ? 

### ISSUE THREAD

**Issue by johntdyer** [nyxcharon/vault-ui#14]
So I wanted to play around with this and Vault.  I've gotten Vault running in dev mode and your container running, but I am not sure what to put in as my username and password for your UI....

**Comment by SydOps** [comment]
Same here @nyxcharon 

What's the default user/pass?

**Comment by nyxcharon** [comment]
There is no default username or pass. You need to mount the userpass backend and configure at least one user. The user will only be able to view what their role(s) allows.

https://www.vaultproject.io/docs/auth/userpass.html

**Comment by nyxcharon** [comment]
Fixed with commit 0b1f4ba
