### ISSUE TITLE
User env vars default in package.json overrides user specified

### ISSUE THREAD

**Issue by flaccid** [nyxcharon/vault-ui#6]
In particular for `CONSUL_HOST` and `VAULT_HOST` these are currently explicitly set in `package.json` so effectively overriding the variable values if the user sets them e.g. when using docker.

e.g.
```
    "start-prod-api": {
      "command": "node ./bin/api.js",
      "env": {
        "NODE_PATH": "./api",
        "NODE_ENV": "production",
        "API_PORT": 3030,
        "VAULT_HOST": "vault.service.consul",
        "CONSUL_HOST": "consul.service.consul"
      }
    },
```

The defaulting should probably occur in `config.js`.

**Comment by nyxcharon** [comment]
Fixed by #7
